# Generated by Django 3.1.3 on 2021-03-22 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import fin.models.ticker.ticker


class Migration(migrations.Migration):

    replaces = [('fin', '0001_initial'), ('fin', '0002_auto_20200511_2151'), ('fin', '0003_auto_20200519_1238'), ('fin', '0004_auto_20200524_1322'), ('fin', '0005_auto_20200607_0113'), ('fin', '0006_auto_20200617_0105'), ('fin', '0007_tickerstatement'), ('fin', '0008_auto_20200903_1458'), ('fin', '0009_auto_20200921_0916'), ('fin', '0010_auto_20201121_0224'), ('fin', '0011_auto_20201122_0235'), ('fin', '0012_auto_20201123_0328'), ('fin', '0013_portfoliopolicy'), ('fin', '0014_auto_20201128_0356'), ('fin', '0015_auto_20201128_2121'), ('fin', '0016_auto_20201209_1322'), ('fin', '0017_auto_20210201_0229'), ('fin', '0018_auto_20210321_1331'), ('fin', '0019_auto_20210321_2313')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('UAH', 'Ukrainian Hryvnia'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1.000001)])),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_money_amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_money_amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_source_url', models.URLField(choices=[('https://www.slickcharts.com/sp500', 'S&P 500'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='Unknown', max_length=50)),
                ('industry', models.CharField(default='Unknown', max_length=50)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sector', models.CharField(default='Unknown', max_length=50)),
                ('company_name', models.CharField(default='Unknown', max_length=50)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TickerIndexWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1.000001)])),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='fin.index')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='fin.ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='index',
            name='tickers',
            field=models.ManyToManyField(through='fin.TickerIndexWeight', to='fin.Ticker'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioTickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='fin.portfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_ticker', to='fin.ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tickers',
            field=models.ManyToManyField(through='fin.PortfolioTickers', to='fin.Ticker'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fin.portfolio'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='fin_account_name_bad83d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='fin_account_currenc_038c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='index',
            index=models.Index(fields=['data_source_url'], name='fin_index_data_so_42cbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['name'], name='fin_portfol_name_a7ed17_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='fin_portfol_user_id_b18df3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotickers',
            index=models.Index(fields=['portfolio'], name='fin_portfol_portfol_0067d1_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotickers',
            index=models.Index(fields=['ticker'], name='fin_portfol_ticker__afdb91_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['company_name'], name='fin_ticker_company_e63386_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['country'], name='fin_ticker_country_ce69e7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['industry'], name='fin_ticker_industr_fcc10f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['sector'], name='fin_ticker_sector_d03a15_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['symbol'], name='fin_ticker_symbol_dcd8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['index'], name='fin_tickeri_index_i_6fdc10_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['ticker'], name='fin_tickeri_ticker__137ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['weight'], name='fin_tickeri_weight_54393c_idx'),
        ),
        migrations.AlterModelManagers(
            name='ticker',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('outdated_tickers', fin.models.ticker.ticker.OutdatedTickersManager()),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.slickcharts.com/sp500', 'S&P 500'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX')], unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='ticker',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='TickerStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('capital_lease_obligations', 'Capital Lease Obligations'), ('net_income', 'Net Income'), ('price', 'Price'), ('total_assets', 'Total Assets'), ('short_term_debt', 'Short Term Debt'), ('total_long_term_debt', 'Total Long Term Debt'), ('total_revenue', 'Total Revenue'), ('total_shareholder_equity', 'Total Shareholder Equity')], max_length=50)),
                ('fiscal_date_ending', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_statements', to='fin.ticker')),
            ],
            options={
                'abstract': False,
                'unique_together': {('fiscal_date_ending', 'name', 'ticker_id')},
            },
        ),
        migrations.AddField(
            model_name='index',
            name='status',
            field=models.IntegerField(choices=[(0, 'Successfully Updated'), (1, 'Updating'), (2, 'Update Failed')], default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.IntegerField(choices=[(0, 'Successfully Updated'), (1, 'Updating'), (2, 'Update Failed')], default=0),
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.CheckConstraint(check=models.Q(price__gt=0), name='ticker_price_non_negative'),
        ),
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('http://invescopowershares.com/products/overview.aspx?ticker=PBW', 'PBW'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX'), ('https://www.slickcharts.com/sp500', 'S&P 500')], unique=True),
        ),
        migrations.CreateModel(
            name='PortfolioPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asset_to_equity_max_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('asset_to_equity_min_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('debt_to_equity_max_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('max_dividend_payout_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('minimum_annual_earnings_growth', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('pe_quantile', models.IntegerField(default=50)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_policy', to='fin.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='TickerIndexWeight',
            new_name='IndexTicker',
        ),
        migrations.RenameModel(
            old_name='PortfolioTickers',
            new_name='PortfolioTicker',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_index_i_6fdc10_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_ticker__137ec4_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_weight_54393c_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolioticker',
            name='fin_portfol_portfol_0067d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolioticker',
            name='fin_portfol_ticker__afdb91_idx',
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['index'], name='fin_indexti_index_i_f63d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['ticker'], name='fin_indexti_ticker__64cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['weight'], name='fin_indexti_weight_d585d3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['portfolio'], name='fin_portfol_portfol_8f19db_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['ticker'], name='fin_portfol_ticker__44841e_idx'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AlterField(
            model_name='tickerstatement',
            name='name',
            field=models.CharField(choices=[('capital_lease_obligations', 'Capital Lease Obligations'), ('net_income', 'Net Income'), ('outstanding_shares', 'Outstanding Shares'), ('price', 'Price'), ('short_term_debt', 'Short Term Debt'), ('total_assets', 'Total Assets'), ('total_long_term_debt', 'Total Long Term Debt'), ('total_revenue', 'Total Revenue'), ('total_shareholder_equity', 'Total Shareholder Equity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239724/ishares-core-sp-total-us-stock-market-etf/1467271812596.ajax', 'ITOT'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('http://invescopowershares.com/products/overview.aspx?ticker=PBW', 'PBW'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX'), ('https://www.slickcharts.com/sp500', 'S&P 500')], unique=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239724/ishares-core-sp-total-us-stock-market-etf/1467271812596.ajax', 'ITOT'), ('https://www.ishares.com/us/products/244048/ishares-core-msci-total-international-stock-etf/1467271812596.ajax', 'IXUS'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('http://invescopowershares.com/products/overview.aspx?ticker=PBW', 'PBW'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX'), ('https://www.slickcharts.com/sp500', 'S&P 500')], unique=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='stock_exchange',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.UniqueConstraint(fields=('stock_exchange', 'symbol'), name='unique_stock_ex_ticker_combination'),
        ),
    ]
