# Generated by Django 3.1.6 on 2021-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexticker',
            name='raw_data',
            field=models.JSONField(default={}),
        ),
    ]
