# Generated by Django 3.1.9 on 2021-06-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchangeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('currency', 'portfolio_id'), name='currency_portfolio_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='portfolioticker',
            constraint=models.UniqueConstraint(fields=('portfolio_id', 'ticker_id'), name='portfolio_id_ticker_id_unique'),
        ),
        migrations.AddField(
            model_name='stockexchangealias',
            name='stock_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.stockexchange'),
        ),
    ]
