# Generated by Django 3.1.8 on 2021-05-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indexticker',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='fin.index'),
        ),
        migrations.AddField(
            model_name='indexticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='fin.ticker'),
        ),
        migrations.AddField(
            model_name='index',
            name='tickers',
            field=models.ManyToManyField(through='fin.IndexTicker', to='fin.Ticker'),
        ),
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fin.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='tickerstatement',
            unique_together={('fiscal_date_ending', 'name', 'ticker_id')},
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['portfolio'], name='fin_portfol_portfol_8f19db_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['ticker'], name='fin_portfol_ticker__44841e_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['name'], name='fin_portfol_name_a7ed17_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='fin_portfol_user_id_b18df3_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['index'], name='fin_indexti_index_i_f63d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['ticker'], name='fin_indexti_ticker__64cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['weight'], name='fin_indexti_weight_d585d3_idx'),
        ),
        migrations.AddIndex(
            model_name='index',
            index=models.Index(fields=['data_source_url'], name='fin_index_data_so_42cbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='fin_account_name_bad83d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='fin_account_currenc_038c9a_idx'),
        ),
    ]
