# Generated by Django 3.1.8 on 2021-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.UniqueConstraint(fields=('stock_exchange', 'symbol', 'cusip', 'isin', 'sedol'), name='stock_exchange_symbol_unique'),
        ),
    ]
