# Generated by Django 3.0.3 on 2020-02-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_source_url', models.URLField(choices=[('https://www.slickcharts.com/sp500', 'S&P 500')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=10, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('deleted', models.BooleanField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='fin.Index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
