# Generated by Django 3.1.9 on 2021-06-08 11:17

from django.db import migrations


def move_aliases(apps, schema_editor):
    StockExchange = apps.get_model('fin', 'StockExchange')
    StockExchangeAlias = apps.get_model('fin', 'StockExchangeAlias')

    stock_exchange_aliases = []
    for stock_exchange in StockExchange.objects.all():
        for alias in stock_exchange.aliases:
            stock_exchange_aliases.append(StockExchangeAlias(stock_exchange=stock_exchange,
                                                             alias=alias))
    StockExchangeAlias.objects.bulk_create(stock_exchange_aliases)



class Migration(migrations.Migration):
    dependencies = [
        ('fin', '0002_auto_20210608_1116'),
    ]

    operations = [
        migrations.RunPython(move_aliases, lambda x, y: None)
    ]
