# Generated by Django 3.1.8 on 2021-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_auto_20210529_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='cusip',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='isin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sedol',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
