# Generated by Django 3.1.8 on 2021-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_indexticker_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://amplifyetfs.com/Data/Feeds/ForesideAmplify.40XL.XL_Holdings.csv', 'IBUY'), ('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239724/ishares-core-sp-total-us-stock-market-etf/1467271812596.ajax', 'ITOT'), ('https://www.ishares.com/us/products/244048/ishares-core-msci-total-international-stock-etf/1467271812596.ajax', 'IXUS'), ('http://invescopowershares.com/products/overview.aspx?ticker=PBW', 'PBW'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX')], unique=True),
        ),
    ]
