# Generated by Django 3.1.9 on 2021-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_auto_20210604_0937'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indexticker',
            constraint=models.UniqueConstraint(fields=('index_id', 'ticker_id'), name='index_ticker_unique'),
        ),
    ]
