# Generated by Django 3.0.4 on 2020-05-24 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_auto_20200519_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='index',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='weight',
        ),
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.slickcharts.com/sp500', 'S&P 500'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000')], unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TickerIndexWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1.000001)])),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='fin.Index')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='fin.Ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='index',
            name='tickers',
            field=models.ManyToManyField(through='fin.TickerIndexWeight', to='fin.Ticker'),
        ),
    ]
