# Generated by Django 3.1.8 on 2021-06-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_auto_20210529_1444'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticker',
            name='unique_stock_ex_ticker_combination',
        ),
    ]
