# Generated by Django 3.1.9 on 2021-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_remove_stockexchange_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexchange',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
