# Generated by Django 3.0.7 on 2020-06-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_auto_20200607_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotickers',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_ticker', to='fin.Ticker'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name'], name='fin_account_name_bad83d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='fin_account_currenc_038c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='index',
            index=models.Index(fields=['data_source_url'], name='fin_index_data_so_42cbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['name'], name='fin_portfol_name_a7ed17_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='fin_portfol_user_id_b18df3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotickers',
            index=models.Index(fields=['portfolio'], name='fin_portfol_portfol_0067d1_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotickers',
            index=models.Index(fields=['ticker'], name='fin_portfol_ticker__afdb91_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['company_name'], name='fin_ticker_company_e63386_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['country'], name='fin_ticker_country_ce69e7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['industry'], name='fin_ticker_industr_fcc10f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['sector'], name='fin_ticker_sector_d03a15_idx'),
        ),
        migrations.AddIndex(
            model_name='ticker',
            index=models.Index(fields=['symbol'], name='fin_ticker_symbol_dcd8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['index'], name='fin_tickeri_index_i_6fdc10_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['ticker'], name='fin_tickeri_ticker__137ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='tickerindexweight',
            index=models.Index(fields=['weight'], name='fin_tickeri_weight_54393c_idx'),
        ),
    ]
