# Generated by Django 3.1.8 on 2021-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_auto_20210601_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exante_account_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
