# Generated by Django 3.1.8 on 2021-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_portfolio_exante_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='exante_account_id',
            field=models.CharField(max_length=50),
        ),
    ]
