# Generated by Django 3.0.7 on 2020-08-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_auto_20200617_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('capital_lease_obligations', 'Capital Lease Obligations'), ('net_income', 'Net Income'), ('debt', 'Debt'), ('price', 'Price'), ('total_assets', 'Total Assets'), ('short_term_debt', 'Short Term Debt'), ('total_long_term_debt', 'Total Long Term Debt'), ('total_revenue', 'Total Revenue'), ('total_shareholder_equity', 'Total Shareholder Equity')], max_length=50)),
                ('fiscal_date_ending', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_statements', to='fin.Ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
