# Generated by Django 3.1.9 on 2021-06-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_remove_portfolio_exante_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExanteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exante_account_id', models.CharField(max_length=50)),
                ('iss', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fin.portfolio')),
            ],
        ),
    ]
