# Generated by Django 3.0.7 on 2020-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0007_tickerstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
