# Generated by Django 3.1.9 on 2021-07-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0007_exantesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fin.source'),
        ),
    ]
