# Generated by Django 3.0.7 on 2020-09-05 00:51

from django.db import migrations
import django.db.models.manager
import fin.models.ticker.ticker


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20200825_1231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticker',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('outdated_tickers', fin.models.ticker.ticker.OutdatedTickersManager()),
            ],
        ),
    ]
