# Generated by Django 3.0.7 on 2020-09-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20200903_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tickerstatement',
            unique_together={('fiscal_date_ending', 'name', 'ticker_id')},
        ),
    ]
