# Generated by Django 3.1.8 on 2021-06-02 14:44

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20210602_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexchange',
            name='aliases',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
