# Generated by Django 3.0.7 on 2020-09-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20200903_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tickerstatement',
            unique_together={('fiscal_date_ending', 'name')},
        ),
    ]
