# Generated by Django 3.0.7 on 2020-09-03 13:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20200825_1231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticker',
            managers=[
                ('outdated_tickers', django.db.models.manager.Manager()),
            ],
        ),
    ]
