# Generated by Django 3.1.8 on 2021-06-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0009_auto_20210602_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='stock_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.stockexchange'),
        ),
    ]
