# Generated by Django 3.0.7 on 2020-11-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0009_auto_20200921_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='status',
            field=models.IntegerField(choices=[(0, 'Successfully Updated'), (1, 'Updating'), (2, 'Update Failed')], default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.IntegerField(choices=[(0, 'Successfully Updated'), (1, 'Updating'), (2, 'Update Failed')], default=0),
        ),
    ]
