# Generated by Django 3.0.7 on 2020-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0011_auto_20201122_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='data_source_url',
            field=models.URLField(choices=[('https://www.ishares.com/us/products/239516/ishares-us-medical-devices-etf/1467271812596.ajax', 'IHI'), ('https://www.slickcharts.com/nasdaq100', 'NASDAQ 100'), ('http://invescopowershares.com/products/overview.aspx?ticker=PBW', 'PBW'), ('https://www.ishares.com/us/products/239714/ishares-russell-3000-etf/1467271812596.ajax', 'RUSSEL3000'), ('https://www.ishares.com/us/products/239705/ishares-phlx-semiconductor-etf/1467271812596.ajax', 'SOXX'), ('https://www.slickcharts.com/sp500', 'S&P 500')], unique=True),
        ),
    ]
