# Generated by Django 3.1.3 on 2020-11-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0013_portfoliopolicy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerIndexWeight',
            new_name='IndexTicker',
        ),
        migrations.RenameModel(
            old_name='PortfolioTickers',
            new_name='PortfolioTicker',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_index_i_6fdc10_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_ticker__137ec4_idx',
        ),
        migrations.RemoveIndex(
            model_name='indexticker',
            name='fin_tickeri_weight_54393c_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolioticker',
            name='fin_portfol_portfol_0067d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolioticker',
            name='fin_portfol_ticker__afdb91_idx',
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['index'], name='fin_indexti_index_i_f63d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['ticker'], name='fin_indexti_ticker__64cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='indexticker',
            index=models.Index(fields=['weight'], name='fin_indexti_weight_d585d3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['portfolio'], name='fin_portfol_portfol_8f19db_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioticker',
            index=models.Index(fields=['ticker'], name='fin_portfol_ticker__44841e_idx'),
        ),
    ]
