# Generated by Django 3.1.3 on 2020-11-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0014_auto_20201128_0356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
