# Generated by Django 3.1.3 on 2020-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0015_auto_20201128_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerstatement',
            name='name',
            field=models.CharField(choices=[('capital_lease_obligations', 'Capital Lease Obligations'), ('net_income', 'Net Income'), ('outstanding_shares', 'Outstanding Shares'), ('price', 'Price'), ('short_term_debt', 'Short Term Debt'), ('total_assets', 'Total Assets'), ('total_long_term_debt', 'Total Long Term Debt'), ('total_revenue', 'Total Revenue'), ('total_shareholder_equity', 'Total Shareholder Equity')], max_length=50),
        ),
    ]
